 export const GET_CONTACTS_START = "GET_CONTACTS_START";
 export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
 export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

 export const DELETE_CONTACT_START = "DELETE_CONTACT_START";
 export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
 export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

 export const ADD_CONTACT_START = "ADD_CONTACT_START";
 export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
 export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

 export const EDIT_CONTACT_START = "EDIT_CONTACT_START";
 export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
 export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";